leftnav:
- identifier: 35a4eb51-53ed-bddd-cb5f-22aa6c8bf08e
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: a19973cf-4d04-17be-1719-84a18a6dfb83
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 453ed948-3355-0754-533e-3bea2d1f1816
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 30
- identifier: fe61d394-8fb4-9eed-17ea-a372d9b74ea7
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
- identifier: 6984f061-5cd9-9ab6-bd71-77abde1fc132
  name: Projects
  pageRef: /pages/projects
  weight: 50
